// Library function implementation, LLVM-style.

// See script_LLVM for more ramblings about the LLVM ScriptEngine.

// Turn off warnings generated by LLVM; I don't really care to fix them and I don't
// want them clogging up my compile output.
#pragma warning(disable:4146)
#pragma warning(disable:4996)
#pragma warning(disable:4800)

#include "core.h"
#include "script.h"

#include "llvm/Linker.h"
#include "llvm/LLVMContext.h"
#include "llvm/Module.h"
#include "llvm/DerivedTypes.h"
#include "llvm/Constants.h"
#include "llvm/Instructions.h"
#include "llvm/ModuleProvider.h"
#include "llvm/Analysis/Verifier.h"
#include "llvm/ExecutionEngine/ExecutionEngine.h"
#include "llvm/ExecutionEngine/Interpreter.h"
#include "llvm/ExecutionEngine/JIT.h"
#include "llvm/ExecutionEngine/GenericValue.h"
#include "llvm/Support/raw_ostream.h"
#include "llvm/Support/MemoryBuffer.h"
#include "llvm/System/DynamicLibrary.h"
#include "llvm/Bitcode/ReaderWriter.h"

// use the llvm namespace so we're not forever typing "llvm::"
using namespace llvm;

#define SCRIPT_FUNCTION(FUNC_NAME) GenericValue FUNC_NAME(FunctionType *ft, const std::vector<GenericValue> &args)

static GenericValue nullGV;

SCRIPT_FUNCTION(testCall) {
	Log::debug("testCall() has executed.");
	return nullGV;
}

SCRIPT_FUNCTION(writeStringToLog) {
	Log::write((char *)args[0].PointerVal);
	return nullGV;
}

// ---

void ScriptEngine::registerEggLibraryFunctions() {
	std::vector<ScriptEngine::type> *arglist;

	registerFunction(testCall, "testCall", VoidType);
	
	arglist = new std::vector<ScriptEngine::type>(1, PointerType);
	registerFunction(writeStringToLog, "log", VoidType, arglist);
}