// Library function implementation, LLVM-style.

// See script_LLVM for more ramblings about the LLVM ScriptEngine.

// Turn off warnings generated by LLVM; I don't really care to fix them and I don't
// want them clogging up my compile output.
#pragma warning(disable:4146)
#pragma warning(disable:4996)
#pragma warning(disable:4800)

#include "core.h"
#include "script.h"

#include "llvm/Linker.h"
#include "llvm/LLVMContext.h"
#include "llvm/Module.h"
#include "llvm/DerivedTypes.h"
#include "llvm/Constants.h"
#include "llvm/Instructions.h"
#include "llvm/ModuleProvider.h"
#include "llvm/Analysis/Verifier.h"
#include "llvm/ExecutionEngine/ExecutionEngine.h"
#include "llvm/ExecutionEngine/Interpreter.h"
#include "llvm/ExecutionEngine/JIT.h"
#include "llvm/ExecutionEngine/GenericValue.h"
#include "llvm/Support/raw_ostream.h"
#include "llvm/Support/MemoryBuffer.h"
#include "llvm/System/DynamicLibrary.h"
#include "llvm/Bitcode/ReaderWriter.h"

// use the llvm namespace so we're not forever typing "llvm::"
using namespace llvm;

#define SCRIPT_FUNCTION(FUNC_NAME) GenericValue FUNC_NAME(FunctionType *ft, const std::vector<GenericValue> &args)

static GenericValue nullGV;

// - Testing Built In Functions -

SCRIPT_FUNCTION(testCall) {
	Log::debug("testCall() has executed.");
	return nullGV;
}

SCRIPT_FUNCTION(addOne) {
	GenericValue returnValue;
	returnValue.DoubleVal = args[0].DoubleVal + 1;

	Log::debug("addOne() executed. Returning %g + 1 = %g", args[0].DoubleVal, returnValue.DoubleVal);
	
	return returnValue;
}

SCRIPT_FUNCTION(writeNumberToLog) {
	Log::write("%g", args[0].DoubleVal);
	return nullGV;
}

SCRIPT_FUNCTION(writeStringToLog) {
	Log::write((char *)args[0].PointerVal);
	return nullGV;
}

// ---

void ScriptEngine::registerEggLibraryFunctions() {
	registerFunction(testCall, "testCall", VoidType, 0);
	registerFunction(writeStringToLog, "log", VoidType, 1, PointerType);
	registerFunction(writeNumberToLog, "logNumber", VoidType, 1, NumberType);
	registerFunction(addOne, "addOne", NumberType, 1, NumberType);
}